import { Site, Radar, SiteActivity, Source, Contact } from "./types";

export const seedSources: Source[] = [
  {
    source_id: "SRC-001",
    source_title: "White Sands Missile Range Official Website",
    source_url: "https://www.wsmr.army.mil/",
    source_type: "Official",
    publisher: "U.S. Army",
    access_date: "2026-05-01",
    reliability_score: 95,
  },
  {
    source_id: "SRC-002",
    source_title: "Vandenberg Space Force Base Fact Sheet",
    source_url: "https://www.vandenberg.spaceforce.mil/",
    source_type: "Official",
    publisher: "U.S. Space Force",
    access_date: "2026-05-01",
    reliability_score: 95,
  },
  {
    source_id: "SRC-003",
    source_title: "Cape Canaveral Space Force Station",
    source_url: "https://www.patrick.spaceforce.mil/",
    source_type: "Official",
    publisher: "U.S. Space Force",
    access_date: "2026-05-01",
    reliability_score: 95,
  },
  {
    source_id: "SRC-004",
    source_title: "Pacific Missile Range Facility Fact Sheet",
    source_url: "https://www.cnic.navy.mil/regions/cnrh/installations/pacific-missile-range-facility.html",
    source_type: "Official",
    publisher: "U.S. Navy",
    access_date: "2026-05-01",
    reliability_score: 90,
  },
  {
    source_id: "SRC-005",
    source_title: "NASA Wallops Flight Facility",
    source_url: "https://www.nasa.gov/wallops",
    source_type: "Official",
    publisher: "NASA",
    access_date: "2026-05-01",
    reliability_score: 95,
  },
  {
    source_id: "SRC-006",
    source_title: "Eglin Air Force Base - 96th Test Wing",
    source_url: "https://www.eglin.af.mil/",
    source_type: "Official",
    publisher: "U.S. Air Force",
    access_date: "2026-05-01",
    reliability_score: 90,
  },
  {
    source_id: "SRC-007",
    source_title: "Poker Flat Research Range - University of Alaska",
    source_url: "https://www.gi.alaska.edu/facilities/poker-flat-research-range",
    source_type: "Academic",
    publisher: "University of Alaska Fairbanks",
    access_date: "2026-05-01",
    reliability_score: 85,
  },
  {
    source_id: "SRC-008",
    source_title: "Tonopah Test Range - Sandia National Laboratories",
    source_url: "https://www.sandia.gov/about/locations/tonopah-test-range/",
    source_type: "Government",
    publisher: "Sandia National Laboratories",
    access_date: "2026-05-01",
    reliability_score: 90,
  },
  {
    source_id: "SRC-009",
    source_title: "Pacific Spaceport Complex – Alaska",
    source_url: "https://akaerospace.com/spaceport/",
    source_type: "Industry",
    publisher: "Alaska Aerospace Corporation",
    access_date: "2026-05-01",
    reliability_score: 80,
  },
  {
    source_id: "SRC-010",
    source_title: "Reagan Test Site - U.S. Army Space and Missile Defense Command",
    source_url: "https://www.smdc.army.mil/Portals/38/Documents/Publications/Fact_Sheets/RTS.pdf",
    source_type: "Official",
    publisher: "U.S. Army SMDC",
    access_date: "2026-05-01",
    reliability_score: 90,
  },
  {
    source_id: "SRC-011",
    source_title: "Wikipedia - White Sands Missile Range",
    source_url: "https://en.wikipedia.org/wiki/White_Sands_Missile_Range",
    source_type: "Encyclopedia",
    publisher: "Wikimedia Foundation",
    access_date: "2026-05-01",
    reliability_score: 75,
    notes: "Publicly sourced encyclopedia article with references to official DoD and Army sources.",
  },
  {
    source_id: "SRC-012",
    source_title: "Federation of American Scientists - U.S. Range Instrumentation",
    source_url: "https://fas.org/",
    source_type: "Research",
    publisher: "Federation of American Scientists",
    access_date: "2026-05-01",
    reliability_score: 80,
    notes: "Non-partisan research organization providing analysis of national security topics.",
  },
  {
    source_id: "SRC-013",
    source_title: "Missile Defense Agency - Fact Sheets and Resources",
    source_url: "https://www.mda.mil/news/fact_sheets.html",
    source_type: "Official",
    publisher: "U.S. Missile Defense Agency",
    access_date: "2026-05-01",
    reliability_score: 95,
    notes: "Official MDA fact sheets covering test infrastructure and range capabilities.",
  },
  {
    source_id: "SRC-014",
    source_title: "MIT Lincoln Laboratory - Kwajalein Field Site",
    source_url: "https://www.ll.mit.edu/about/facilities/kwajalein-field-site",
    source_type: "Academic",
    publisher: "MIT Lincoln Laboratory",
    access_date: "2026-05-01",
    reliability_score: 90,
    notes: "MIT Lincoln Laboratory operates and maintains several radar systems at the Reagan Test Site.",
  },
  {
    source_id: "SRC-015",
    source_title: "GlobalSecurity.org - U.S. Military Test Ranges",
    source_url: "https://www.globalsecurity.org/military/facility/",
    source_type: "Research",
    publisher: "GlobalSecurity.org",
    access_date: "2026-05-01",
    reliability_score: 70,
    notes: "Public information resource for military facilities and weapons systems.",
  },
];

export const seedSites: Site[] = [
  {
    site_id: "SITE-001",
    site_name: "White Sands Missile Range",
    site_type: "Range",
    size_category: "Strategic / Mega",
    size_score: 95,
    country: "USA",
    state: "New Mexico",
    latitude: 32.3831,
    longitude: -106.4781,
    coordinate_type: "Site centroid",
    managing_organization: "U.S. Army Test and Evaluation Command",
    operator: "U.S. Army",
    missile_relevance:
      "Primary U.S. Army missile testing range since 1945. Supports developmental and operational testing of virtually all Army missile systems including Patriot, THAAD, Javelin, Stinger, and Hellfire. Also supports Navy, Air Force, and allied nation missile programs. Historical test site for the first atomic bomb detonation (Trinity Test, 1945) and early V-2 rocket tests captured from Germany.",
    launch_relevance:
      "Sounding rocket launches and high-altitude research. Hosts NASA suborbital launches. Historically supported early space program rocket tests including V-2, WAC Corporal, and Aerobee sounding rockets.",
    radar_relevance:
      "Operates a dense network of tracking, surveillance, and telemetry radars across the range for flight safety and data collection during missile tests. Includes the MOTR multi-object tracking radar, legacy AN/FPS-16 precision trackers, the AN/MPS-25 search radar, the AN/TPQ-39 tracking radar, and multiple Doppler weather/range radars.",
    website: "https://www.wsmr.army.mil/",
    description:
      "White Sands Missile Range (WSMR) is the largest military installation in the United States, spanning approximately 3,200 square miles (8,300 km²) across the Tularosa Basin in south-central New Mexico. Established on 9 July 1945 as the White Sands Proving Ground, it was created to support testing of captured German V-2 rockets and quickly expanded to become the nation's premier overland missile test range. The range stretches roughly 100 miles north-to-south and 40 miles east-to-west, bordered by the San Andres and Organ Mountains to the west and the Sacramento Mountains to the east. WSMR supports testing of missiles, rockets, directed energy weapons, unmanned aerial systems, and other defense technologies for the Army, Navy, Air Force, Marines, NASA, and allied nations. Key facilities include the Launch Complex 33 historical site (first V-2 launch in the U.S.), numerous static test stands, the High Energy Laser Systems Test Facility (HELSTF), and the WSMR instrumentation complex with optical trackers, telemetry stations, and a dense radar network. The range also contains the Trinity Site, where the world's first nuclear device was detonated on 16 July 1945. WSMR employs over 11,000 civilian and military personnel and contributes significantly to the regional economy.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-002",
    site_name: "Vandenberg Space Force Base",
    site_type: "Launch Site",
    size_category: "Strategic / Mega",
    size_score: 92,
    country: "USA",
    state: "California",
    latitude: 34.7333,
    longitude: -120.5667,
    coordinate_type: "Site centroid",
    managing_organization: "U.S. Space Force - Space Launch Delta 30",
    operator: "U.S. Space Force",
    missile_relevance:
      "ICBM test launches including Minuteman III operational test launches (Glory Trip series). Historical test site for Atlas, Titan II, Peacekeeper (MX), and Midgetman ICBMs. Serves as the primary west coast ICBM test launch facility for U.S. Strategic Command force readiness testing.",
    launch_relevance:
      "Major west coast launch site for polar and sun-synchronous orbit missions. Active launch providers include SpaceX (SLC-4E, Falcon 9/Heavy), ULA (SLC-3E, Atlas V/Vulcan), and the Space Force. Historically launched reconnaissance, weather, and communications satellites. SpaceX Starship operations are planned at SLC-6.",
    radar_relevance:
      "Operates the Western Range instrumentation complex, including multiple C-band metric tracking radars, AN/FPS-16 precision trackers, AN/MPS-36 tracking radars, and telemetry receive antennas supporting launch vehicle tracking and range safety from liftoff through orbital insertion.",
    website: "https://www.vandenberg.spaceforce.mil/",
    description:
      "Vandenberg Space Force Base (VSFB) is a U.S. Space Force installation located on the central California coast near Lompoc, approximately 170 miles northwest of Los Angeles. Covering roughly 99,600 acres (156 square miles), the base sits on a strategic coastal promontory that allows southward launch trajectories over open ocean, making it ideal for polar and sun-synchronous orbit missions. Originally established as Camp Cooke in 1941, it was transferred to the Air Force in 1957 and renamed Vandenberg AFB in 1958 after General Hoyt S. Vandenberg, the second Air Force Chief of Staff. The base became a Space Force installation in 2021. Vandenberg hosts Space Launch Delta 30 (formerly the 30th Space Wing), which manages the Western Range extending thousands of miles across the Pacific Ocean. The base contains over a dozen launch complexes, including active pads for SpaceX Falcon 9/Heavy (SLC-4E), ULA Atlas V and Vulcan (SLC-3E), and ICBM test silos for Minuteman III. Vandenberg has conducted over 2,000 launches since 1958, including the first polar-orbit satellite launch (Discoverer 1, 1959). The Western Range instrumentation network features tracking radars, telemetry stations, optical cameras, and command destruct systems along the California coast and on downrange islands.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-003",
    site_name: "Cape Canaveral Space Force Station",
    site_type: "Launch Site",
    size_category: "Strategic / Mega",
    size_score: 96,
    country: "USA",
    state: "Florida",
    latitude: 28.4889,
    longitude: -80.5778,
    coordinate_type: "Site centroid",
    managing_organization: "U.S. Space Force - Space Launch Delta 45",
    operator: "U.S. Space Force",
    missile_relevance:
      "Historical birthplace of American ballistic missile testing. First launches of Atlas, Titan, Minuteman, Polaris, Pershing, and other missile systems. Eastern Range supports flight testing and missile defense interceptor launches. Cape Canaveral has hosted over 3,500 launches since 1950.",
    launch_relevance:
      "Primary east coast launch site. Active pads support SpaceX (SLC-40, Falcon 9/Heavy), ULA (SLC-41, Atlas V/Vulcan), Blue Origin (LC-36, New Glenn), and Relativity Space (LC-16). Adjacent to NASA Kennedy Space Center for Shuttle-era and Artemis/SLS operations. Handles the majority of U.S. national security space launches to geosynchronous and low-Earth orbits.",
    radar_relevance:
      "Eastern Range operates a comprehensive network of C-band and S-band tracking radars, including the AN/FPQ-14 precision tracking radar, AN/TPQ-18 tracking radars, and multiple mobile and fixed radar assets distributed across Cape Canaveral, Patrick SFB, Jonathan Dickinson Missile Tracking Annex, and downrange stations in the Bahamas and Ascension Island.",
    website: "https://www.patrick.spaceforce.mil/",
    description:
      "Cape Canaveral Space Force Station (CCSFS) is a U.S. Space Force installation on Cape Canaveral, Florida, occupying approximately 15,800 acres on a barrier island along Florida's Atlantic coast. It is one of the busiest and most historically significant launch sites in the world, with over 3,500 launches since its first missile flight in 1950 (a Bumper V-2 rocket). The station is managed by Space Launch Delta 45 (formerly the 45th Space Wing), which also operates the Eastern Range stretching over 10,000 miles across the Atlantic Ocean to the Indian Ocean. CCSFS hosts more than 30 launch complexes, several of which remain active for modern launch vehicles. SpaceX conducts high-tempo Falcon 9 and Falcon Heavy launches from SLC-40, ULA operates Atlas V and Vulcan Centaur from SLC-41, and Blue Origin has constructed its New Glenn launch pad at LC-36. Historical pads include LC-5/6 (Redstone/Mercury), LC-13 (Atlas), LC-14 (Atlas/John Glenn orbital flight), LC-19 (Titan/Gemini), and LC-34/37 (Saturn I/IB). The station houses the Air Force Space and Missile Museum. Cape Canaveral is adjacent to NASA's Kennedy Space Center on Merritt Island, and the two installations share infrastructure and range safety systems. The Eastern Range instrumentation complex includes tracking radars, telemetry stations, flight termination systems, meteorological assets, and optical tracking cameras spread across mainland Florida, Grand Bahama Island, Antigua, and Ascension Island.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-004",
    site_name: "Reagan Test Site (Kwajalein Atoll)",
    site_type: "Range",
    size_category: "Large",
    size_score: 78,
    country: "USA",
    state: "Marshall Islands",
    latitude: 8.7181,
    longitude: 167.7328,
    coordinate_type: "Site centroid",
    managing_organization: "U.S. Army Space and Missile Defense Command",
    operator: "U.S. Army",
    missile_relevance:
      "Premier U.S. instrumented test site for ballistic missile defense. Serves as the primary impact and intercept area for ICBM reentry vehicle testing and Ground-Based Midcourse Defense (GMD) intercept tests. Targets launched from Vandenberg AFB and PSCA Alaska fly approximately 4,800 miles to the Kwajalein lagoon. Supports Missile Defense Agency test campaigns.",
    radar_relevance:
      "Home to one of the world's most capable radar complexes, operated by MIT Lincoln Laboratory and the U.S. Army. Includes ALTAIR (VHF/UHF deep-space tracking), TRADEX (L/S-band target discrimination), ALCOR (C-band wideband imaging), MMW (millimeter-wave radar), and the KREMS (Kiernan Reentry Measurements Site) radars. These systems provide precision tracking, signature collection, and imaging of reentry vehicles and space objects.",
    website: "https://www.smdc.army.mil/",
    description:
      "The Ronald Reagan Ballistic Missile Defense Test Site (RTS) is located on Kwajalein Atoll in the Republic of the Marshall Islands, approximately 2,300 miles southwest of Honolulu, Hawaii. The atoll is the world's largest coral atoll, encompassing a lagoon of approximately 839 square miles with 97 islands and islets. The U.S. Army has operated on Kwajalein since 1944, and the site was renamed in 1999 to honor President Ronald Reagan for his role in advancing missile defense. RTS is the principal instrumented test range for ballistic missile defense testing, providing the downrange impact area for ICBMs launched from Vandenberg AFB and the Pacific Spaceport Complex in Alaska. The site operates some of the most powerful and precise tracking radars in the world, managed by MIT Lincoln Laboratory under contract to the U.S. Army. These radars — including ALTAIR, TRADEX, ALCOR, MMW, and KREMS systems — perform deep-space surveillance, precision tracking of reentry vehicles, target discrimination experiments, and high-resolution radar imaging. RTS also supports NASA space surveillance missions and contributes data to the Space Surveillance Network. The primary installations are on Kwajalein Island (administrative hub), Roi-Namur Island (radar complex), and Meck Island (interceptor launch facility for GMD tests). Approximately 2,500 U.S. personnel and contractors reside on the atoll.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-005",
    site_name: "Pacific Missile Range Facility",
    site_type: "Range",
    size_category: "Large",
    size_score: 75,
    country: "USA",
    state: "Hawaii",
    latitude: 22.0394,
    longitude: -159.7853,
    coordinate_type: "Site centroid",
    managing_organization: "U.S. Navy",
    operator: "U.S. Navy",
    missile_relevance:
      "Primary test facility for Aegis Ballistic Missile Defense system. Hosts Standard Missile (SM-3, SM-6) intercept tests, THAAD flight tests, and cooperative engagement capability exercises. Supports both target missile launches and interceptor launches for missile defense testing.",
    launch_relevance:
      "Supports missile defense target launches, interceptor test launches, and short-range ballistic missile target operations. Launch facilities include the Barking Sands Tactical Underwater Range launch pads and the Makaha Ridge launch complex.",
    radar_relevance:
      "Operates multiple tracking and fire-control radars including mobile AN/TPY-2 THAAD radar deployments, SPY-1 radar system testing platforms, the AN/SPY-6(V) Air and Missile Defense Radar test facility, and fixed C-band tracking radars for range instrumentation and flight safety.",
    website:
      "https://www.cnic.navy.mil/regions/cnrh/installations/pacific-missile-range-facility.html",
    description:
      "Pacific Missile Range Facility (PMRF), located on the western coast of Kauai, Hawaii, is the world's largest instrumented multi-environment range, capable of simultaneously supporting surface, subsurface, air, and space operations. The facility encompasses approximately 1,100 square miles of instrumented underwater range and over 42,000 square miles of controlled airspace. Established in 1956, PMRF has grown into the premier Pacific test and training range for the U.S. military. The facility's remote open-ocean location provides 360 degrees of open-water range, ideal for live-fire missile testing without hazard to civilian populations. PMRF supports Aegis Ballistic Missile Defense (BMD) testing, THAAD missile defense exercises, torpedo and anti-submarine warfare testing, undersea surveillance system evaluations, and joint multi-service training exercises such as RIMPAC (Rim of the Pacific). The range is instrumented with tracking radars, optical systems, telemetry stations, and the Barking Sands Tactical Underwater Range (BARSTUR) and Barking Sands Underwater Range Extension (BSURE) for submarine and torpedo operations. PMRF also hosts the Aegis Ashore test facility, a land-based version of the Aegis Combat System used for missile defense testing and system development. Approximately 1,500 military and civilian personnel are assigned to the facility.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-006",
    site_name: "NASA Wallops Flight Facility",
    site_type: "Launch Site",
    size_category: "Medium",
    size_score: 48,
    country: "USA",
    state: "Virginia",
    latitude: 37.9400,
    longitude: -75.4661,
    coordinate_type: "Site centroid",
    managing_organization: "NASA Goddard Space Flight Center",
    operator: "NASA",
    launch_relevance:
      "One of the oldest and most active launch ranges in the world. Supports sounding rocket launches, small orbital launch vehicles (Antares, Minotaur), and scientific balloon flights. The adjacent Mid-Atlantic Regional Spaceport (MARS) hosts Northrop Grumman Antares/Cygnus cargo resupply missions to the International Space Station. Over 16,000 rockets have been launched from Wallops since 1945.",
    radar_relevance:
      "Operates tracking radars for launch range safety and flight tracking, including C-band tracking radars for sounding rocket and orbital launch support, and mobile radar units for campaign-specific deployments.",
    website: "https://www.nasa.gov/wallops",
    description:
      "NASA Wallops Flight Facility (WFF) is located on the Eastern Shore of Virginia's Delmarva Peninsula, approximately 150 miles southeast of Washington, D.C. Established in 1945 by the National Advisory Committee for Aeronautics (NACA, NASA's predecessor) as a site for aerodynamic research using rocket-propelled models, Wallops has grown into one of the most versatile launch facilities in the world. The facility consists of three separate land areas — the Main Base (research and administrative facilities), Wallops Mainland (rocket storage, assembly, and payload processing), and Wallops Island (launch pads and range control). Wallops Island contains six active launch pads supporting rockets from small sounding rockets to medium-class orbital launch vehicles. The facility has launched over 16,000 rockets since its founding, more than any other launch site in the United States by count. In addition to NASA missions, Wallops hosts the Mid-Atlantic Regional Spaceport (MARS), a commercial spaceport operated by the Virginia Commercial Space Flight Authority, which supports Northrop Grumman Antares/Cygnus ISS cargo resupply missions and other commercial launches. Wallops also manages NASA's suborbital sounding rocket program, the Scientific Balloon Program, and operates the Wallops Range supporting both NASA and Department of Defense missions. The range instrumentation includes tracking radars, telemetry receivers, optical trackers, and meteorological systems. Approximately 1,200 civil servants and 3,000 contractors work at the facility.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-007",
    site_name: "Eglin Air Force Base / Gulf Test Range",
    site_type: "Range",
    size_category: "Large",
    size_score: 72,
    country: "USA",
    state: "Florida",
    latitude: 30.4750,
    longitude: -86.5256,
    coordinate_type: "Site centroid",
    managing_organization: "U.S. Air Force - 96th Test Wing",
    operator: "U.S. Air Force",
    missile_relevance:
      "Air-to-air and air-to-ground missile developmental and operational testing, including AIM-120 AMRAAM, AIM-9X Sidewinder, AGM-158 JASSM, AGM-88 HARM, JDAM, Small Diameter Bomb (SDB), and hypersonic weapon prototypes. The 96th Test Wing conducts first-article testing and operational evaluation for virtually all USAF air-delivered weapons.",
    radar_relevance:
      "Home to the AN/FPS-85 phased-array space surveillance radar, one of the most powerful radar systems in the U.S. Space Surveillance Network. Also operates the 96th Range Group's network of test instrumentation radars including C-band precision trackers, the AN/FPS-24 search radar, mobile tracking radars, and has supported ground testing of airborne radar systems such as JSTARS (E-8C) APY-7 radar and F-35 APG-81 AESA radar.",
    website: "https://www.eglin.af.mil/",
    description:
      "Eglin Air Force Base is a U.S. Air Force installation covering approximately 464,000 acres (724 square miles) in the Florida panhandle, making it the largest Air Force base in the Western Hemisphere by area. The reservation spans portions of Santa Rosa, Okaloosa, and Walton counties in northwest Florida. The base was established in 1935 as the Valparaiso Bombing and Gunnery Base and played a critical role in World War II as a training and weapons development center, including preparation of the Doolittle Raiders for their historic 1942 bombing mission against Japan. Today, Eglin is home to the 96th Test Wing, the Air Force's most diverse test organization, responsible for developmental testing and evaluation of air-delivered conventional weapons, electronic combat systems, navigation and guidance systems, command and control systems, and air-to-ground and air-to-air munitions. The Gulf Test Range extends over 120,000 square miles of water range in the Gulf of Mexico, providing vast airspace and sea space for weapons testing. Eglin also hosts the 33rd Fighter Wing (F-35 Lightning II training), the 7th Special Forces Group, and numerous tenant organizations. The AN/FPS-85, located at the base, is the only phased-array radar in the Space Surveillance Network dedicated to tracking objects in Earth orbit. Range instrumentation includes tracking radars, telemetry stations, optical systems, scoring cameras, and the Eglin Test and Training Complex electronic warfare threat simulation systems. Over 10,000 military and 5,000 civilian personnel are assigned to the base.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-008",
    site_name: "Poker Flat Research Range",
    site_type: "Range",
    size_category: "Small",
    size_score: 22,
    country: "USA",
    state: "Alaska",
    latitude: 65.1211,
    longitude: -147.4700,
    coordinate_type: "Site centroid",
    managing_organization:
      "University of Alaska Fairbanks - Geophysical Institute",
    operator: "University of Alaska Fairbanks",
    launch_relevance:
      "Sounding rocket launches for aurora, upper atmosphere, and space physics research. The only university-operated rocket launch range in the United States. Supports NASA Sounding Rocket Program campaigns and international scientific collaborations.",
    radar_relevance:
      "Operates a tracking radar for launch safety and vehicle flight monitoring during sounding rocket campaigns. Also co-located with Geophysical Institute ionospheric research radars used for upper-atmosphere science.",
    website:
      "https://www.gi.alaska.edu/facilities/poker-flat-research-range",
    description:
      "Poker Flat Research Range (PFRR) is the only university-operated rocket launch facility in the United States and the largest land-based research rocket range in the world. Located approximately 30 miles (48 km) north of Fairbanks, Alaska at a geographic latitude of 65.13°N, the range is situated beneath the auroral oval, making it an ideal location for studying the aurora borealis and the physics of the near-Earth space environment. The range was established in 1968 by the Geophysical Institute of the University of Alaska Fairbanks with support from NASA. Poker Flat covers approximately 5,132 acres of launch and impact areas, with a controlled downrange area extending into the Yukon-Tanana uplands. The range has launched over 3,000 sounding rockets since its founding, carrying scientific payloads to altitudes ranging from 50 to over 900 miles. Launch campaigns are typically conducted during the winter months (November-March) when dark skies maximize aurora observation. The range operates multiple launch pads supporting a variety of sounding rocket motors, from small Super Arcas meteorological rockets to large multi-stage Black Brant and Terrier-Improved Orion vehicles. Supporting infrastructure includes telemetry receiving stations, optical cameras, magnetometers, riometers, lidar systems, and a tracking radar for flight safety. The range is funded primarily by NASA and the National Science Foundation and collaborates with researchers from around the world.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-009",
    site_name: "Tonopah Test Range",
    site_type: "Range",
    size_category: "Medium",
    size_score: 45,
    country: "USA",
    state: "Nevada",
    latitude: 37.7981,
    longitude: -116.7806,
    coordinate_type: "Site centroid",
    managing_organization: "Sandia National Laboratories / DOE NNSA",
    operator: "Sandia National Laboratories",
    missile_relevance:
      "Weapons delivery accuracy testing for nuclear weapon shapes and fusing/firing systems. Ballistic trajectory testing for gravity bombs and reentry vehicle shapes. Supports stockpile stewardship program testing. Historical test site for F-117 stealth fighter development in the 1980s.",
    radar_relevance:
      "Operates a network of precision tracking radars for weapon drop testing, including high-accuracy C-band trackers and cinetheodolites for trajectory measurement. Radar data is used for scoring weapon delivery accuracy and characterizing ballistic flight performance.",
    website: "https://www.sandia.gov/about/locations/tonopah-test-range/",
    description:
      "Tonopah Test Range (TTR) is a restricted-access facility operated by Sandia National Laboratories under the auspices of the U.S. Department of Energy's National Nuclear Security Administration (NNSA). The range is located in the high desert of central Nevada, approximately 170 miles northwest of Las Vegas, within the boundaries of the Nevada Test and Training Range (NTTR). TTR encompasses approximately 625 square miles (280 square miles of the primary impact area) of arid terrain at an average elevation of about 5,500 feet. The range has been operational since 1957, when it was established by Sandia Corporation (now Sandia National Laboratories) for testing non-nuclear components of nuclear weapons. TTR's primary mission is evaluating the ballistic performance, delivery accuracy, and fuzing and firing systems of nuclear weapon shapes dropped from aircraft. Test operations involve aircraft releasing instrumented test units at various altitudes, with a network of precision tracking radars, cinetheodolites, optical cameras, and scoring systems recording the trajectory and impact point. The range also supports testing of gravity-dispensed cluster munitions, penetrator weapons, and parachute-retarded systems. TTR played a significant historical role in the development of the F-117 Nighthawk stealth fighter, with the aircraft based at the Tonopah Test Range Airport from 1982 until the program was publicly acknowledged in 1988. Today, TTR continues to support NNSA's stockpile stewardship program and Department of Defense weapons qualification testing. Approximately 200 Sandia personnel work at the range.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
  {
    site_id: "SITE-010",
    site_name: "Pacific Spaceport Complex – Alaska (Kodiak)",
    site_type: "Launch Site",
    size_category: "Small",
    size_score: 20,
    country: "USA",
    state: "Alaska",
    latitude: 57.4333,
    longitude: -152.3333,
    coordinate_type: "Site centroid",
    managing_organization: "Alaska Aerospace Corporation",
    operator: "Alaska Aerospace Corporation",
    launch_relevance:
      "Orbital and suborbital launches supporting polar, sun-synchronous, and high-inclination orbit missions from Kodiak Island. The only FAA-licensed launch facility not co-located with a federal range. Launched the first orbital mission from a non-federal range in the U.S. in 2001 (Kodiak Star / Athena I).",
    missile_relevance:
      "Supports Missile Defense Agency target missile launches for GMD and Aegis BMD testing campaigns. Target missiles launched from PSCA fly across the Pacific to the Reagan Test Site at Kwajalein Atoll. Has served as a target launch site for multiple operational missile defense flight tests.",
    website: "https://akaerospace.com/spaceport/",
    description:
      "Pacific Spaceport Complex – Alaska (PSCA), formerly known as the Kodiak Launch Complex, is a dual-use commercial and government launch facility located on Narrow Cape at the southeastern tip of Kodiak Island, Alaska. The complex occupies approximately 3,717 acres of state-owned land and became operational in 1998. PSCA is the only FAA-licensed spaceport in the United States that is not co-located with a federal launch range, operating under its own FAA launch license and providing its own range safety. The site's geographic location at 57.4°N latitude is advantageous for launching into high-inclination, polar, and sun-synchronous orbits, as southward trajectories over the open Pacific Ocean avoid overflying populated areas. PSCA has two launch pads: Launch Pad 1 (LP-1) supports suborbital and small orbital vehicles, and Launch Pad 2 (LP-2) supports larger orbital-class rockets. The facility achieved a historic milestone in 2001 when an Athena I rocket launched from Kodiak became the first orbital mission from a non-federal launch range. PSCA has supported multiple Missile Defense Agency target launches, with intermediate-range ballistic missile targets launched toward the Kwajalein Atoll impact area for Ground-Based Midcourse Defense intercept tests. The complex includes vehicle and payload processing buildings, a launch control center, tracking and telemetry systems, and range safety infrastructure. The facility is managed and operated by Alaska Aerospace Corporation, a state-owned corporation.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    record_status: "Published",
  },
];

export const seedRadars: Radar[] = [
  // ── SITE-001: White Sands Missile Range (7 radars) ──
  {
    radar_id: "RAD-001",
    site_id: "SITE-001",
    radar_name: "MOTR (Multiple Object Tracking Radar)",
    radar_type: "Tracking",
    frequency_band: "S-band",
    purpose:
      "Simultaneous tracking of multiple airborne objects during missile test flights, providing real-time trajectory data for range safety and test evaluation",
    operator: "U.S. Army",
    manufacturer: "Lockheed Martin",
    operational_status: "Active",
    public_description:
      "The MOTR system at White Sands provides simultaneous tracking of multiple targets during missile test flights. It is capable of tracking up to 100 objects concurrently, making it essential for complex test scenarios involving multiple missiles, targets, and debris. MOTR uses a phased-array antenna to rapidly switch between tracked objects.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-001",
    record_status: "Published",
  },
  {
    radar_id: "RAD-002",
    site_id: "SITE-001",
    radar_name: "AN/FPS-16 Tracking Radar",
    radar_model: "AN/FPS-16",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision single-target tracking of missiles and rockets during flight testing",
    manufacturer: "RCA",
    operator: "U.S. Army",
    installation_date: "1958",
    operational_status: "Active",
    public_description:
      "The AN/FPS-16 is a C-band monopulse precision tracking radar originally developed by RCA in the 1950s. At White Sands, these radars provide high-accuracy angular and range tracking of missiles and rockets during flight tests. The system achieves angular accuracy of approximately 0.1 mil and range accuracy of a few yards, making it a workhorse for instrumentation tracking at test ranges worldwide.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-001",
    record_status: "Published",
  },
  {
    radar_id: "RAD-003",
    site_id: "SITE-001",
    radar_name: "AN/MPS-25 Search Radar",
    radar_model: "AN/MPS-25",
    radar_type: "Surveillance",
    frequency_band: "S-band",
    purpose:
      "Range surveillance and acquisition of test targets before handoff to precision tracking radars",
    operator: "U.S. Army",
    operational_status: "Active",
    public_description:
      "The AN/MPS-25 is a transportable S-band search radar used at White Sands for range surveillance. It provides initial target detection and acquisition during missile tests, feeding target coordinates to precision tracking radars for handoff. The radar covers a wide volume of airspace over the range.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-011",
    record_status: "Published",
  },
  {
    radar_id: "RAD-004",
    site_id: "SITE-001",
    radar_name: "AN/TPQ-39 Tracking Radar",
    radar_model: "AN/TPQ-39",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "High-precision tracking of missile and drone targets for test scoring and evaluation",
    operator: "U.S. Army",
    manufacturer: "RCA / General Electric",
    operational_status: "Active",
    public_description:
      "The AN/TPQ-39 is a transportable C-band precision tracking radar deployed at White Sands Missile Range. It provides accurate position data on missiles and aerial targets during developmental and operational test missions, contributing to miss-distance scoring and flight safety.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-011",
    record_status: "Published",
  },
  {
    radar_id: "RAD-005",
    site_id: "SITE-001",
    radar_name: "WSMR Search and Surveillance Radar",
    radar_type: "Surveillance",
    frequency_band: "L-band",
    purpose:
      "Long-range search and airspace surveillance for range safety and test coordination",
    operator: "U.S. Army",
    operational_status: "Active",
    public_description:
      "White Sands operates L-band search radars that provide wide-area airspace surveillance across the 3,200 square mile range complex. These radars ensure range airspace is clear of non-participating aircraft before and during missile tests and support range safety by tracking all airborne objects in the test area.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-001",
    record_status: "Published",
  },
  {
    radar_id: "RAD-006",
    site_id: "SITE-001",
    radar_name: "WSMR Doppler Weather/Range Radar",
    radar_type: "Weather/range radar",
    frequency_band: "C-band",
    purpose:
      "Meteorological data collection and wind profiling for range operations and test planning",
    operator: "U.S. Army",
    operational_status: "Active",
    public_description:
      "White Sands operates Doppler weather radar systems to provide real-time meteorological data critical for missile test planning and range safety decisions. Wind profiles, precipitation, and atmospheric conditions are monitored to support go/no-go decisions and post-flight data correction for wind effects on missile trajectories.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-001",
    record_status: "Published",
  },
  {
    radar_id: "RAD-007",
    site_id: "SITE-001",
    radar_name: "WSMR Telemetry Tracking Radar",
    radar_type: "Telemetry",
    frequency_band: "S-band",
    purpose:
      "Tracking and receiving real-time telemetry data from missiles and rockets during flight",
    operator: "U.S. Army",
    operational_status: "Active",
    public_description:
      "White Sands operates S-band telemetry tracking radars that auto-track the telemetry signal from missiles and rockets during flight tests. These systems simultaneously track the vehicle and receive downlinked telemetry data including guidance performance, structural loads, and warhead fuzing parameters, providing engineers with real-time test data.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-001",
    record_status: "Published",
  },

  // ── SITE-002: Vandenberg Space Force Base (5 radars) ──
  {
    radar_id: "RAD-008",
    site_id: "SITE-002",
    radar_name: "AN/FPS-16 Western Range Tracking Radar",
    radar_model: "AN/FPS-16",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision tracking of launch vehicles for Western Range flight safety",
    operator: "U.S. Space Force",
    manufacturer: "RCA",
    operational_status: "Active",
    public_description:
      "The Western Range operates AN/FPS-16 C-band precision tracking radars at Vandenberg to provide high-accuracy tracking of launch vehicles from liftoff through stage separation. These radars feed real-time position data to the Range Safety Officer for flight termination decisions.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-002",
    record_status: "Published",
  },
  {
    radar_id: "RAD-009",
    site_id: "SITE-002",
    radar_name: "AN/MPS-36 Tracking Radar",
    radar_model: "AN/MPS-36",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision metric tracking of launch vehicles and ICBMs during flight test",
    manufacturer: "RCA",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The AN/MPS-36 is a transportable C-band monopulse tracking radar used on the Western Range for precision tracking of launch vehicles and ICBM test flights. It provides accurate range, azimuth, and elevation data for trajectory reconstruction and range safety.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-002",
    record_status: "Published",
  },
  {
    radar_id: "RAD-010",
    site_id: "SITE-002",
    radar_name: "Western Range Metric Radar Network",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Network of metric tracking radars distributed along the California coast for launch vehicle tracking through powered flight",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The Western Range maintains a distributed network of C-band metric tracking radars positioned along the coast from Vandenberg to Point Mugu. These radars provide overlapping coverage to continuously track launch vehicles during the critical powered flight phase, ensuring redundant tracking data for range safety.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-002",
    record_status: "Published",
  },
  {
    radar_id: "RAD-011",
    site_id: "SITE-002",
    radar_name: "Western Range Telemetry Tracking Antenna",
    radar_type: "Telemetry",
    frequency_band: "S-band",
    purpose:
      "Auto-tracking telemetry receive system for downlink of launch vehicle and ICBM flight data",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The Western Range operates large-aperture S-band telemetry tracking antennas at Vandenberg and downrange sites to receive real-time telemetry from launch vehicles and ICBM test flights. These systems auto-track the vehicle's telemetry transmitter and provide engineers with continuous flight performance data.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-002",
    record_status: "Published",
  },
  {
    radar_id: "RAD-012",
    site_id: "SITE-002",
    radar_name: "Western Range Search/Surveillance Radar",
    radar_type: "Surveillance",
    frequency_band: "L-band",
    purpose:
      "Airspace surveillance for range safety clearance before and during launch operations",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "Vandenberg operates surveillance radars to monitor airspace over the Western Range launch corridors, ensuring that no non-participating aircraft or vessels are in danger zones during launch and ICBM test operations. These radars support the Range Safety Officer's airspace clearance decisions.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-002",
    record_status: "Published",
  },

  // ── SITE-003: Cape Canaveral Space Force Station (6 radars) ──
  {
    radar_id: "RAD-013",
    site_id: "SITE-003",
    radar_name: "AN/FPQ-14 Precision Tracking Radar",
    radar_model: "AN/FPQ-14",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "High-precision tracking of launch vehicles on the Eastern Range for flight safety and trajectory data",
    manufacturer: "RCA / Raytheon",
    operator: "U.S. Space Force",
    installation_date: "1964",
    upgrade_date: "2005",
    operational_status: "Active",
    public_description:
      "The AN/FPQ-14 is a high-power C-band precision tracking radar operated on the Eastern Range. Upgraded from the AN/FPS-16 design, the FPQ-14 provides improved range and accuracy for tracking launch vehicles from Cape Canaveral through powered flight. It is one of the primary metric tracking radars used for real-time flight safety data.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-003",
    record_status: "Published",
  },
  {
    radar_id: "RAD-014",
    site_id: "SITE-003",
    radar_name: "AN/TPQ-18 Tracking Radar",
    radar_model: "AN/TPQ-18",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision metric tracking of launch vehicles for Eastern Range operations",
    manufacturer: "RCA",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The AN/TPQ-18 is a transportable C-band precision tracking radar deployed at multiple locations on the Eastern Range. These radars provide accurate position data on launch vehicles during flight, supporting the Range Safety Officer with real-time tracking data for flight termination decisions.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-003",
    record_status: "Published",
  },
  {
    radar_id: "RAD-015",
    site_id: "SITE-003",
    radar_name: "Eastern Range C-Band Tracking Radar Network",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Distributed network of tracking radars from Florida through downrange stations for continuous launch vehicle tracking",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The Eastern Range operates a network of C-band tracking radars at Cape Canaveral, Patrick SFB, Jonathan Dickinson Missile Tracking Annex (JDMTA), Grand Bahama Island, and Antigua. This distributed network provides continuous tracking of launch vehicles from liftoff through orbit insertion, with overlapping coverage to ensure no tracking gaps during the critical ascent phase.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-003",
    record_status: "Published",
  },
  {
    radar_id: "RAD-016",
    site_id: "SITE-003",
    radar_name: "Eastern Range S-Band Telemetry System",
    radar_type: "Telemetry",
    frequency_band: "S-band",
    purpose:
      "Receiving and recording real-time telemetry from launch vehicles during Eastern Range operations",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The Eastern Range S-band telemetry systems consist of auto-tracking antennas at multiple sites along the range that receive real-time flight data from launch vehicles. Telemetry data includes vehicle guidance performance, propulsion parameters, structural loads, and payload status, enabling range safety decisions and post-flight analysis.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-003",
    record_status: "Published",
  },
  {
    radar_id: "RAD-017",
    site_id: "SITE-003",
    radar_name: "Eastern Range Surveillance Radar",
    radar_type: "Surveillance",
    frequency_band: "L-band",
    purpose:
      "Airspace and sea-surface surveillance for range clearance during launch operations",
    operator: "U.S. Space Force",
    operational_status: "Active",
    public_description:
      "The Eastern Range operates surveillance radars to monitor airspace and sea lanes along launch trajectories from Cape Canaveral eastward over the Atlantic Ocean. These radars ensure launch corridors are clear of non-participating aircraft and vessels prior to launch, supporting the Launch Decision Authority's go/no-go determination.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-003",
    record_status: "Published",
  },
  {
    radar_id: "RAD-018",
    site_id: "SITE-003",
    radar_name: "Patrick SFB AN/FPQ-14 Downrange Tracker",
    radar_model: "AN/FPQ-14",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Downrange precision tracking at Patrick Space Force Base for Eastern Range launch operations",
    operator: "U.S. Space Force",
    manufacturer: "Raytheon",
    operational_status: "Active",
    public_description:
      "A second AN/FPQ-14 precision tracking radar is located at Patrick Space Force Base, south of Cape Canaveral, providing an alternate tracking angle and extended coverage for launch vehicles as they fly downrange over the Atlantic. This radar complements the Cape Canaveral trackers to maintain continuous precision tracking through the critical first minutes of flight.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-003",
    record_status: "Published",
  },

  // ── SITE-004: Reagan Test Site / Kwajalein Atoll (6 radars) ──
  {
    radar_id: "RAD-019",
    site_id: "SITE-004",
    radar_name: "ALTAIR (ARPA Long-Range Tracking and Instrumentation Radar)",
    radar_model: "ALTAIR",
    radar_type: "Phased-array",
    frequency_band: "VHF/UHF",
    purpose:
      "Deep space surveillance, satellite tracking, and long-range ballistic missile tracking",
    operator: "U.S. Army",
    manufacturer: "MIT Lincoln Laboratory",
    installation_date: "1970",
    operational_status: "Active",
    public_description:
      "ALTAIR is a high-power VHF/UHF dual-frequency radar located on Roi-Namur Island at Kwajalein Atoll. Operated by MIT Lincoln Laboratory, it is capable of tracking objects at ranges exceeding 20,000 miles, making it one of the most powerful tracking radars in the world. ALTAIR supports ballistic missile defense testing by tracking incoming reentry vehicles, contributes to the Space Surveillance Network by cataloging objects in deep space, and has been used for scientific studies of the near-Earth asteroid and space debris environment.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-010",
    record_status: "Published",
  },
  {
    radar_id: "RAD-020",
    site_id: "SITE-004",
    radar_name: "TRADEX (Target Resolution and Discrimination Experiment)",
    radar_model: "TRADEX",
    radar_type: "Tracking",
    frequency_band: "L/S-band",
    purpose:
      "Ballistic missile target tracking, signature measurement, and discrimination experiments",
    operator: "U.S. Army",
    manufacturer: "MIT Lincoln Laboratory / RCA",
    installation_date: "1963",
    operational_status: "Active",
    public_description:
      "TRADEX is a high-power dual-frequency (L-band and S-band) tracking radar on Roi-Namur Island, originally built in 1963 as part of Project PRESS (Pacific Range Electromagnetic Signature Studies). TRADEX performs precision tracking of ballistic missile reentry vehicles and collects radar signature data used for target discrimination — distinguishing warheads from decoys and debris. It has been extensively upgraded over its six decades of operation and remains a critical sensor for missile defense data collection.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-010",
    record_status: "Published",
  },
  {
    radar_id: "RAD-021",
    site_id: "SITE-004",
    radar_name: "ALCOR (ARPA-Lincoln C-Band Observables Radar)",
    radar_model: "ALCOR",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Wideband high-resolution tracking and range-Doppler imaging of reentry vehicles and space objects",
    operator: "U.S. Army",
    manufacturer: "MIT Lincoln Laboratory",
    installation_date: "1970",
    operational_status: "Active",
    public_description:
      "ALCOR is a wideband C-band radar on Roi-Namur Island providing high-resolution range-Doppler imaging of reentry vehicles, satellites, and space debris. With its extremely wide bandwidth, ALCOR can produce radar images that reveal the physical shape and structure of tracked objects, enabling detailed analysis of reentry vehicle characteristics and threat-object discrimination for missile defense programs.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-010",
    record_status: "Published",
  },
  {
    radar_id: "RAD-022",
    site_id: "SITE-004",
    radar_name: "MMW (Millimeter-Wave Radar)",
    radar_model: "MMW",
    radar_type: "Tracking",
    frequency_band: "Ka-band",
    purpose:
      "Ultra-high-resolution radar imaging of reentry vehicles and space objects at millimeter wavelengths",
    operator: "U.S. Army",
    manufacturer: "MIT Lincoln Laboratory / Raytheon",
    installation_date: "1983",
    operational_status: "Active",
    public_description:
      "The MMW (Millimeter-Wave) radar on Roi-Namur operates at Ka-band frequencies, providing the highest resolution radar imaging capability at the Reagan Test Site. Its extremely short wavelength enables detailed imaging of reentry vehicle features, payload deployment events, and debris characterization. MMW complements the lower-frequency ALCOR and TRADEX radars by adding fine-detail imaging data to the multi-sensor picture.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-014",
    record_status: "Published",
  },
  {
    radar_id: "RAD-023",
    site_id: "SITE-004",
    radar_name: "KREMS (Kiernan Reentry Measurements Site) Radars",
    radar_type: "Tracking",
    frequency_band: "C/X-band",
    purpose:
      "Multi-sensor reentry measurement complex for ballistic missile defense data collection",
    operator: "U.S. Army",
    manufacturer: "MIT Lincoln Laboratory",
    installation_date: "1967",
    operational_status: "Active",
    public_description:
      "The Kiernan Reentry Measurements Site (KREMS) on Roi-Namur Island is a multi-sensor complex that includes tracking radars, optical telescopes, and signal collection systems. KREMS provides a comprehensive data collection capability for characterizing ballistic missile reentry phenomena, including wake effects, ablation signatures, and debris behavior. The site is named after Major General Joseph P. Kiernan, a pioneer in missile defense research.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-014",
    record_status: "Published",
  },
  {
    radar_id: "RAD-024",
    site_id: "SITE-004",
    radar_name: "RTS Space Surveillance Radar",
    radar_type: "Surveillance",
    frequency_band: "UHF",
    purpose:
      "Continuous space surveillance and satellite cataloging in support of the Space Surveillance Network",
    operator: "U.S. Army",
    operational_status: "Active",
    public_description:
      "The Reagan Test Site contributes to the U.S. Space Surveillance Network through dedicated surveillance sensors that continuously track and catalog objects in Earth orbit. The equatorial location of Kwajalein Atoll provides a unique vantage point for observing objects in low-inclination orbits that may not be visible from higher-latitude sensors in the continental United States.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-010",
    record_status: "Published",
  },

  // ── SITE-005: Pacific Missile Range Facility (5 radars) ──
  {
    radar_id: "RAD-025",
    site_id: "SITE-005",
    radar_name: "PMRF C-Band Tracking Radars",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision tracking of missiles and targets during weapons testing and range operations",
    operator: "U.S. Navy",
    operational_status: "Active",
    public_description:
      "PMRF operates multiple C-band precision tracking radars that provide high-accuracy position data on missiles, targets, and interceptors during live-fire test events. These radars support Aegis BMD testing, THAAD flight tests, and other weapons evaluation programs by providing independent metric tracking data for miss-distance scoring and trajectory reconstruction.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-004",
    record_status: "Published",
  },
  {
    radar_id: "RAD-026",
    site_id: "SITE-005",
    radar_name: "AN/TPY-2 THAAD Radar (Mobile Deployment)",
    radar_model: "AN/TPY-2",
    radar_type: "Phased-array",
    frequency_band: "X-band",
    purpose:
      "THAAD missile defense system radar for target detection, tracking, discrimination, and fire control",
    manufacturer: "Raytheon",
    operator: "U.S. Army",
    operational_status: "Active",
    public_description:
      "The AN/TPY-2 is the fire-control radar for the Terminal High Altitude Area Defense (THAAD) system. At PMRF, the AN/TPY-2 is deployed during THAAD flight test campaigns to detect, track, and discriminate incoming ballistic missile targets and guide THAAD interceptors to engagement. The X-band phased-array radar is one of the most capable transportable radars in the U.S. missile defense architecture.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-013",
    record_status: "Published",
  },
  {
    radar_id: "RAD-027",
    site_id: "SITE-005",
    radar_name: "Aegis Ashore SPY-1 Radar Test Facility",
    radar_model: "AN/SPY-1",
    radar_type: "Phased-array",
    frequency_band: "S-band",
    purpose:
      "Land-based Aegis Combat System testing for missile defense development and verification",
    manufacturer: "Lockheed Martin",
    operator: "U.S. Navy / MDA",
    installation_date: "2006",
    operational_status: "Active",
    public_description:
      "The Aegis Ashore Missile Defense Test Complex at PMRF houses a land-based version of the Aegis Combat System, including the AN/SPY-1 phased-array radar. This facility enables testing and validation of Aegis BMD software and hardware upgrades without requiring a ship at sea. It has been used for numerous Standard Missile-3 (SM-3) and SM-6 intercept tests and supports development of new BMD capabilities before fleet deployment.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-013",
    record_status: "Published",
  },
  {
    radar_id: "RAD-028",
    site_id: "SITE-005",
    radar_name: "AN/SPY-6(V) AMDR Test System",
    radar_model: "AN/SPY-6(V)",
    radar_type: "Phased-array",
    frequency_band: "S-band",
    purpose:
      "Land-based testing of the Air and Missile Defense Radar for next-generation destroyer and cruiser integration",
    manufacturer: "Raytheon",
    operator: "U.S. Navy",
    installation_date: "2019",
    operational_status: "Active",
    public_description:
      "PMRF hosts a land-based test facility for the AN/SPY-6(V) Air and Missile Defense Radar (AMDR), the next-generation radar being installed on DDG-51 Flight III Arleigh Burke-class destroyers. The SPY-6 uses scalable Radar Modular Assemblies (RMAs) and provides significantly greater sensitivity and capability than the SPY-1 radar it replaces. The PMRF test facility allows radar performance evaluation against live missile defense targets before fleet integration.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-013",
    record_status: "Published",
  },
  {
    radar_id: "RAD-029",
    site_id: "SITE-005",
    radar_name: "PMRF Surveillance and Range Safety Radar",
    radar_type: "Surveillance",
    frequency_band: "S-band",
    purpose:
      "Range surveillance and safety monitoring for air and sea danger zones during live-fire operations",
    operator: "U.S. Navy",
    operational_status: "Active",
    public_description:
      "PMRF operates surveillance radars that monitor the extensive air and sea danger zones around the facility during live-fire test events. These radars track aircraft and surface vessels to ensure they remain outside hazard areas, supporting the Range Safety Officer's decisions during missile launches and weapons testing exercises.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-004",
    record_status: "Published",
  },

  // ── SITE-006: NASA Wallops Flight Facility (3 radars) ──
  {
    radar_id: "RAD-030",
    site_id: "SITE-006",
    radar_name: "Wallops C-Band Tracking Radar",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision tracking of sounding rockets and orbital launch vehicles for range safety",
    operator: "NASA",
    operational_status: "Active",
    public_description:
      "Wallops Flight Facility operates C-band tracking radars that provide precision position data on rockets from liftoff through burnout. These radars are the primary metric tracking assets for the Wallops Range, supporting both suborbital sounding rocket launches and Antares/Minotaur orbital launches from the Mid-Atlantic Regional Spaceport.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-005",
    record_status: "Published",
  },
  {
    radar_id: "RAD-031",
    site_id: "SITE-006",
    radar_name: "Wallops Mobile Range Safety Radar",
    radar_type: "Surveillance",
    frequency_band: "S-band",
    purpose:
      "Airspace and sea-surface surveillance for range clearance and launch safety",
    operator: "NASA",
    operational_status: "Active",
    public_description:
      "Wallops operates mobile surveillance radar units to support range safety during launch operations. These radars monitor the launch hazard area offshore in the Atlantic Ocean to verify that ships and aircraft are clear of danger zones before launch commit. Mobile radar units can be deployed to optimize coverage for different launch trajectories.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-005",
    record_status: "Published",
  },
  {
    radar_id: "RAD-032",
    site_id: "SITE-006",
    radar_name: "Wallops Telemetry Tracking Antenna",
    radar_type: "Telemetry",
    frequency_band: "S-band",
    purpose:
      "Auto-tracking telemetry receive system for sounding rocket and orbital launch vehicle data",
    operator: "NASA",
    operational_status: "Active",
    public_description:
      "Wallops operates S-band auto-tracking telemetry antennas that receive real-time flight data from rockets during launch. The telemetry data stream includes vehicle health parameters, guidance system performance, and payload data that enable mission controllers to monitor flight progress and make range safety decisions.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-005",
    record_status: "Published",
  },

  // ── SITE-007: Eglin Air Force Base / Gulf Test Range (5 radars) ──
  {
    radar_id: "RAD-033",
    site_id: "SITE-007",
    radar_name: "AN/FPS-85 Space Surveillance Phased-Array Radar",
    radar_model: "AN/FPS-85",
    radar_type: "Phased-array",
    frequency_band: "UHF",
    purpose:
      "Space surveillance and satellite tracking for the U.S. Space Surveillance Network",
    manufacturer: "Bendix / L3Harris",
    operator: "U.S. Space Force",
    installation_date: "1969",
    upgrade_date: "2019",
    operational_status: "Active",
    public_description:
      "The AN/FPS-85 at Eglin AFB is the only phased-array radar in the Space Surveillance Network dedicated exclusively to tracking objects in Earth orbit. The massive transmit and receive arrays (each over 10,000 square feet) face southward toward the equator, enabling detection and tracking of satellites and debris in low, medium, and geosynchronous Earth orbits. The system can track over 200 objects simultaneously and has cataloged thousands of space objects since its activation in 1969. It underwent a major modernization in the 2010s, replacing analog signal processing with digital systems.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-006",
    record_status: "Published",
  },
  {
    radar_id: "RAD-034",
    site_id: "SITE-007",
    radar_name: "Eglin C-Band Precision Tracking Radars",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision tracking of air-to-air and air-to-ground weapons during developmental testing over the Gulf Test Range",
    operator: "U.S. Air Force",
    operational_status: "Active",
    public_description:
      "The 96th Range Group at Eglin operates C-band precision tracking radars that track missiles, munitions, and target drones during weapons developmental testing. These radars provide accurate trajectory data for evaluating weapon guidance performance, scoring miss distances, and reconstructing engagement geometries over the Gulf Test Range.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-006",
    record_status: "Published",
  },
  {
    radar_id: "RAD-035",
    site_id: "SITE-007",
    radar_name: "AN/FPS-24 Long-Range Search Radar",
    radar_model: "AN/FPS-24",
    radar_type: "Surveillance",
    frequency_band: "L-band",
    purpose:
      "Long-range airspace surveillance for range safety and test coordination over the Gulf Test Range",
    operator: "U.S. Air Force",
    installation_date: "1960",
    operational_status: "Active",
    public_description:
      "The AN/FPS-24 is a high-power L-band long-range search radar at Eglin that monitors the vast Gulf Test Range airspace for range safety purposes. It detects and tracks all aircraft in the test area, ensuring that non-participating traffic is identified and cleared before weapons testing begins. The radar's long detection range provides early warning of airspace incursions.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-012",
    record_status: "Published",
  },
  {
    radar_id: "RAD-036",
    site_id: "SITE-007",
    radar_name: "Eglin Mobile Test Instrumentation Radars",
    radar_type: "Tracking",
    frequency_band: "X-band",
    purpose:
      "Deployable precision radars for specialized weapons testing and scoring at various range locations",
    operator: "U.S. Air Force",
    operational_status: "Active",
    public_description:
      "Eglin maintains a fleet of mobile instrumentation radars that can be positioned at optimal locations across the 724-square-mile reservation and Gulf Test Range for specific test events. These X-band radars provide high-resolution tracking data for weapons miss-distance scoring, drone target tracking, and specialized test instrumentation needs that cannot be met by fixed radar sites.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-006",
    record_status: "Published",
  },
  {
    radar_id: "RAD-037",
    site_id: "SITE-007",
    radar_name: "Eglin Radar Cross-Section (RCS) Measurement Facility",
    radar_type: "Tracking",
    frequency_band: "X-band",
    purpose:
      "Ground-based radar signature measurement and characterization of weapons, aircraft, and targets",
    operator: "U.S. Air Force",
    operational_status: "Active",
    public_description:
      "Eglin AFB hosts radar cross-section measurement facilities used for characterizing the radar signature of aircraft, missiles, munitions, and targets. These specialized radars operate across multiple frequency bands and support both developmental testing (reducing signatures of new systems) and threat characterization (measuring signatures of foreign materiel for electronic warfare development).",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-006",
    record_status: "Published",
  },

  // ── SITE-008: Poker Flat Research Range (2 radars) ──
  {
    radar_id: "RAD-038",
    site_id: "SITE-008",
    radar_name: "Poker Flat Tracking Radar",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Flight safety tracking of sounding rockets during launch campaigns",
    operator: "University of Alaska Fairbanks",
    operational_status: "Active",
    public_description:
      "Poker Flat Research Range operates a C-band tracking radar for flight safety during sounding rocket launch campaigns. The radar tracks rockets from liftoff through burnout, providing real-time position data to the Range Safety Officer. If a rocket deviates from its planned trajectory toward populated areas, the tracking data supports the flight termination decision.",
    confidence_level: "High",
    last_verified_date: "2026-05-01",
    source_id: "SRC-007",
    record_status: "Published",
  },
  {
    radar_id: "RAD-039",
    site_id: "SITE-008",
    radar_name: "Poker Flat Ionospheric Research Radar",
    radar_type: "Surveillance",
    frequency_band: "VHF",
    purpose:
      "Scientific study of the ionosphere, aurora, and upper atmosphere above the launch range",
    operator: "University of Alaska Fairbanks",
    operational_status: "Active",
    public_description:
      "Co-located with the launch range, the Geophysical Institute operates VHF ionospheric research radars that probe the structure and dynamics of the ionosphere and auroral phenomena above Poker Flat. These radars complement the sounding rocket measurements by providing continuous ground-based data on the upper atmosphere that sounding rocket payloads sample during their brief flights through the aurora.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-007",
    record_status: "Published",
  },

  // ── SITE-009: Tonopah Test Range (3 radars) ──
  {
    radar_id: "RAD-040",
    site_id: "SITE-009",
    radar_name: "Tonopah C-Band Precision Tracking Radar",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "High-accuracy tracking of weapon test units during ballistic drop tests",
    operator: "Sandia National Laboratories",
    operational_status: "Active",
    public_description:
      "Tonopah Test Range operates C-band precision tracking radars that follow instrumented weapon test units from aircraft release through impact. These radars provide the primary metric data for scoring weapon delivery accuracy, measuring ballistic coefficients, and validating weapon trajectory models. The tracking data, combined with GPS and optical measurements, achieves high-accuracy impact-point determination.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-008",
    record_status: "Published",
  },
  {
    radar_id: "RAD-041",
    site_id: "SITE-009",
    radar_name: "Tonopah Scoring/Impact Radar",
    radar_type: "Tracking",
    frequency_band: "X-band",
    purpose:
      "Terminal-phase weapon tracking and precision impact-point scoring",
    operator: "Sandia National Laboratories",
    operational_status: "Active",
    public_description:
      "Tonopah operates X-band scoring radars positioned near the designated impact areas that provide high-accuracy tracking of weapon test units during the terminal phase of flight. These radars capture the final moments before impact, enabling precise measurement of delivery accuracy (circular error probable) that is critical for nuclear weapon certification.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-008",
    record_status: "Published",
  },
  {
    radar_id: "RAD-042",
    site_id: "SITE-009",
    radar_name: "Tonopah Range Surveillance Radar",
    radar_type: "Surveillance",
    frequency_band: "S-band",
    purpose:
      "Airspace surveillance for range safety and test area clearance",
    operator: "Sandia National Laboratories",
    operational_status: "Active",
    public_description:
      "Tonopah Test Range operates a surveillance radar for monitoring the restricted airspace above the range. Before and during weapon drop tests, this radar verifies that the airspace is clear of unauthorized aircraft. It also provides general air-traffic awareness for coordination with adjacent military airspace managed by Nellis AFB and the Nevada Test and Training Range.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-008",
    record_status: "Published",
  },

  // ── SITE-010: Pacific Spaceport Complex – Alaska (2 radars) ──
  {
    radar_id: "RAD-043",
    site_id: "SITE-010",
    radar_name: "PSCA C-Band Range Safety Tracking Radar",
    radar_type: "Tracking",
    frequency_band: "C-band",
    purpose:
      "Precision tracking of launch vehicles and target missiles for range safety",
    operator: "Alaska Aerospace Corporation",
    operational_status: "Active",
    public_description:
      "PSCA operates a C-band tracking radar for range safety during orbital and suborbital launch operations. The radar tracks rockets from liftoff through burnout, providing real-time position and velocity data to the Range Safety Officer. As PSCA operates under its own FAA launch license rather than a federal range, this radar is a critical independent safety asset.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-009",
    record_status: "Published",
  },
  {
    radar_id: "RAD-044",
    site_id: "SITE-010",
    radar_name: "PSCA Telemetry Tracking System",
    radar_type: "Telemetry",
    frequency_band: "S-band",
    purpose:
      "Receiving real-time flight data from launch vehicles and target missiles",
    operator: "Alaska Aerospace Corporation",
    operational_status: "Active",
    public_description:
      "PSCA operates an S-band telemetry tracking system that receives real-time flight data from launch vehicles and MDA target missiles during powered flight. The system auto-tracks the vehicle's telemetry transmitter and downlinks performance data to the launch control center for mission monitoring and range safety support.",
    confidence_level: "Medium",
    last_verified_date: "2026-05-01",
    source_id: "SRC-009",
    record_status: "Published",
  },
];

export const seedActivities: SiteActivity[] = [
  // ── SITE-001: White Sands Missile Range ──
  {
    activity_id: "ACT-001",
    site_id: "SITE-001",
    activity_category: "Missile Test",
    activity_description:
      "Developmental and operational testing of U.S. Army tactical and strategic missile systems including Patriot (PAC-2/PAC-3), THAAD, Javelin, Stinger, TOW, Hellfire/JAGM, and HIMARS/GMLRS. Also supports Navy, Air Force, and allied nation missile tests.",
    missile_or_system_type:
      "Patriot, THAAD, Javelin, Stinger, Hellfire, JAGM, GMLRS, ATACMS",
    start_year: 1945,
    status: "Current",
    source_id: "SRC-001",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-002",
    site_id: "SITE-001",
    activity_category: "Missile Defense",
    activity_description:
      "Integrated missile defense testing including THAAD and Patriot PAC-3 intercept tests against ballistic missile targets. Supports MDA flight test campaigns and Army Air and Missile Defense modernization programs.",
    missile_or_system_type: "THAAD, Patriot PAC-3, IBCS",
    start_year: 1990,
    status: "Current",
    source_id: "SRC-001",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-003",
    site_id: "SITE-001",
    activity_category: "Space Launch",
    activity_description:
      "Sounding rocket launches for upper atmosphere research. Historically launched V-2 rockets, WAC Corporal, and Aerobee sounding rockets for early space science. Continues to support NASA and university research rocket campaigns.",
    start_year: 1945,
    status: "Current",
    source_id: "SRC-001",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-004",
    site_id: "SITE-001",
    activity_category: "Aerospace Test",
    activity_description:
      "High Energy Laser Systems Test Facility (HELSTF) supports directed energy weapon development and testing. WSMR also hosts drone/UAS testing, electronic warfare exercises, and countermeasure evaluation programs.",
    start_year: 1976,
    status: "Current",
    source_id: "SRC-011",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-005",
    site_id: "SITE-001",
    activity_category: "Radar Tracking",
    activity_description:
      "Continuous range instrumentation operations providing radar tracking, telemetry, and optical coverage for all missile and rocket tests on the range. MOTR and legacy tracking radars provide multi-object tracking across the 3,200 square mile range.",
    start_year: 1945,
    status: "Current",
    source_id: "SRC-001",
    confidence_level: "High",
  },

  // ── SITE-002: Vandenberg Space Force Base ──
  {
    activity_id: "ACT-006",
    site_id: "SITE-002",
    activity_category: "Space Launch",
    activity_description:
      "Polar and sun-synchronous orbit launches for government and commercial payloads. Active launch providers include SpaceX (Falcon 9/Heavy) and ULA (Atlas V/Vulcan Centaur). Over 2,000 launches since 1958.",
    start_year: 1958,
    status: "Current",
    source_id: "SRC-002",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-007",
    site_id: "SITE-002",
    activity_category: "Missile Test",
    activity_description:
      "ICBM test launches including Minuteman III operational test launches (Glory Trip series) from operational-configuration silos. Tests validate ICBM reliability and accuracy for U.S. Strategic Command nuclear deterrence mission.",
    missile_or_system_type: "Minuteman III",
    start_year: 1959,
    status: "Current",
    source_id: "SRC-002",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-008",
    site_id: "SITE-002",
    activity_category: "Range Safety",
    activity_description:
      "Western Range operations providing tracking, telemetry, and flight safety for all launches. Range extends thousands of miles across the Pacific with radar, optical, and telemetry stations on the California coast and downrange sites.",
    start_year: 1958,
    status: "Current",
    source_id: "SRC-002",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-009",
    site_id: "SITE-002",
    activity_category: "Missile Defense",
    activity_description:
      "Launch site for Ground-Based Midcourse Defense (GMD) interceptor test targets. ICBM-class targets are launched from Vandenberg toward the Reagan Test Site at Kwajalein Atoll for intercept testing.",
    missile_or_system_type: "GMD target vehicles",
    start_year: 1999,
    status: "Current",
    source_id: "SRC-013",
    confidence_level: "High",
  },

  // ── SITE-003: Cape Canaveral Space Force Station ──
  {
    activity_id: "ACT-010",
    site_id: "SITE-003",
    activity_category: "Space Launch",
    activity_description:
      "Primary east coast launch site supporting national security, civil, and commercial orbital missions. SpaceX, ULA, Blue Origin, and other providers conduct regular launches to LEO, MEO, GEO, and interplanetary trajectories. Over 3,500 launches since 1950.",
    start_year: 1950,
    status: "Current",
    source_id: "SRC-003",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-011",
    site_id: "SITE-003",
    activity_category: "Missile Test",
    activity_description:
      "Historical ballistic missile test site. First launches of Atlas, Titan, Minuteman, Polaris, Jupiter, Thor, and Pershing missile systems. Birthplace of America's ballistic missile and space launch programs.",
    missile_or_system_type:
      "Atlas, Titan, Minuteman, Polaris, Thor, Jupiter, Pershing",
    start_year: 1950,
    end_year: 1970,
    status: "Historical",
    source_id: "SRC-003",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-012",
    site_id: "SITE-003",
    activity_category: "Range Safety",
    activity_description:
      "Eastern Range operations supporting launch safety with tracking radars, telemetry, flight termination systems, and meteorological assets spanning from Florida through Grand Bahama Island, Antigua, and Ascension Island.",
    start_year: 1950,
    status: "Current",
    source_id: "SRC-003",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-013",
    site_id: "SITE-003",
    activity_category: "Telemetry",
    activity_description:
      "Eastern Range telemetry network receives and records real-time flight data from all launch vehicles during ascent. Multi-site antenna network provides continuous coverage from liftoff through orbital insertion.",
    start_year: 1950,
    status: "Current",
    source_id: "SRC-003",
    confidence_level: "High",
  },

  // ── SITE-004: Reagan Test Site ──
  {
    activity_id: "ACT-014",
    site_id: "SITE-004",
    activity_category: "Missile Defense",
    activity_description:
      "Terminal phase ICBM tracking and Ground-Based Midcourse Defense (GMD) intercept testing. RTS serves as the primary impact/intercept area for ICBM targets launched from Vandenberg AFB and PSCA Alaska. Supports all phases of MDA flight testing.",
    missile_or_system_type: "GMD, GBI, ICBM targets",
    start_year: 1960,
    status: "Current",
    source_id: "SRC-010",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-015",
    site_id: "SITE-004",
    activity_category: "Radar Tracking",
    activity_description:
      "Continuous radar operations using ALTAIR, TRADEX, ALCOR, MMW, and KREMS systems for space surveillance, ballistic missile tracking, reentry vehicle characterization, and target discrimination experiments. Contributes data to the Space Surveillance Network.",
    start_year: 1963,
    status: "Current",
    source_id: "SRC-010",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-016",
    site_id: "SITE-004",
    activity_category: "Other",
    activity_description:
      "Space object identification and characterization using the Reagan Test Site radar complex. Provides metric and signature data on satellites, debris, and deep-space objects for the U.S. Space Command space domain awareness mission.",
    start_year: 1970,
    status: "Current",
    source_id: "SRC-014",
    confidence_level: "High",
  },

  // ── SITE-005: Pacific Missile Range Facility ──
  {
    activity_id: "ACT-017",
    site_id: "SITE-005",
    activity_category: "Missile Defense",
    activity_description:
      "Aegis Ballistic Missile Defense system testing including Standard Missile-3 (SM-3) and SM-6 intercept tests. PMRF's Aegis Ashore facility validates BMD software and hardware before fleet deployment.",
    missile_or_system_type: "Aegis BMD, SM-3 Block IA/IB/IIA, SM-6",
    start_year: 1998,
    status: "Current",
    source_id: "SRC-004",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-018",
    site_id: "SITE-005",
    activity_category: "Missile Test",
    activity_description:
      "THAAD missile defense flight testing. PMRF hosts THAAD battery deployments for live-fire intercept tests against ballistic missile targets launched from within the range complex.",
    missile_or_system_type: "THAAD",
    start_year: 2005,
    status: "Current",
    source_id: "SRC-013",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-019",
    site_id: "SITE-005",
    activity_category: "Radar Tracking",
    activity_description:
      "Range instrumentation supporting surface, air, and space operations with tracking radars, optical systems, and the Barking Sands Tactical Underwater Range. Supports the biennial RIMPAC multinational exercise.",
    start_year: 1956,
    status: "Current",
    source_id: "SRC-004",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-020",
    site_id: "SITE-005",
    activity_category: "Aerospace Test",
    activity_description:
      "Testing of the AN/SPY-6(V) Air and Missile Defense Radar at the PMRF land-based test facility. Supports DDG-51 Flight III destroyer radar integration and performance evaluation against live targets.",
    start_year: 2019,
    status: "Current",
    source_id: "SRC-013",
    confidence_level: "High",
  },

  // ── SITE-006: NASA Wallops Flight Facility ──
  {
    activity_id: "ACT-021",
    site_id: "SITE-006",
    activity_category: "Space Launch",
    activity_description:
      "Sounding rocket launches and orbital launches via the Mid-Atlantic Regional Spaceport (MARS). Supports Northrop Grumman Antares/Cygnus ISS cargo resupply missions and other commercial orbital launches. Over 16,000 rockets launched since 1945.",
    start_year: 1945,
    status: "Current",
    source_id: "SRC-005",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-022",
    site_id: "SITE-006",
    activity_category: "Aerospace Test",
    activity_description:
      "NASA scientific balloon program launches from Wallops and remote sites worldwide. Also supports UAS (drone) testing, aeronautic research flights, and Earth science instrument validation missions.",
    start_year: 1960,
    status: "Current",
    source_id: "SRC-005",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-023",
    site_id: "SITE-006",
    activity_category: "Range Safety",
    activity_description:
      "Wallops Range operations supporting launch safety with tracking radars, telemetry, optical systems, and meteorological assets. Provides range services for both NASA and DoD missions.",
    start_year: 1945,
    status: "Current",
    source_id: "SRC-005",
    confidence_level: "High",
  },

  // ── SITE-007: Eglin Air Force Base / Gulf Test Range ──
  {
    activity_id: "ACT-024",
    site_id: "SITE-007",
    activity_category: "Missile Test",
    activity_description:
      "Developmental testing and evaluation of air-to-air missiles (AIM-120 AMRAAM, AIM-9X Sidewinder), air-to-ground missiles (AGM-158 JASSM, AGM-88 HARM), precision guided munitions (JDAM, SDB), and hypersonic weapon prototypes.",
    missile_or_system_type:
      "AIM-120, AIM-9X, AGM-158 JASSM, AGM-88, JDAM, SDB, hypersonic prototypes",
    start_year: 1935,
    status: "Current",
    source_id: "SRC-006",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-025",
    site_id: "SITE-007",
    activity_category: "Radar Tracking",
    activity_description:
      "AN/FPS-85 phased-array radar provides continuous space surveillance and satellite tracking for the U.S. Space Surveillance Network. Capable of tracking thousands of objects simultaneously in Earth orbit.",
    start_year: 1969,
    status: "Current",
    source_id: "SRC-006",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-026",
    site_id: "SITE-007",
    activity_category: "Aerospace Test",
    activity_description:
      "Electronic warfare testing and evaluation, radar cross-section measurement, F-35 Lightning II pilot training (33rd Fighter Wing), and navigation/guidance system testing. The 96th Test Wing is the Air Force's most diverse test organization.",
    start_year: 1941,
    status: "Current",
    source_id: "SRC-006",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-027",
    site_id: "SITE-007",
    activity_category: "Range Safety",
    activity_description:
      "Gulf Test Range operations supporting weapons testing with tracking radars, scoring systems, telemetry, and optical cameras across 120,000 square miles of overwater range in the Gulf of Mexico.",
    start_year: 1935,
    status: "Current",
    source_id: "SRC-006",
    confidence_level: "High",
  },

  // ── SITE-008: Poker Flat Research Range ──
  {
    activity_id: "ACT-028",
    site_id: "SITE-008",
    activity_category: "Aerospace Test",
    activity_description:
      "Sounding rocket launches for aurora, upper atmosphere, and space physics research. Over 3,000 rockets launched since 1968 carrying scientific payloads to study auroral phenomena, ionospheric physics, and magnetospheric processes.",
    start_year: 1968,
    status: "Current",
    source_id: "SRC-007",
    confidence_level: "High",
  },
  {
    activity_id: "ACT-029",
    site_id: "SITE-008",
    activity_category: "Telemetry",
    activity_description:
      "Ground-based ionospheric and auroral measurements using radars, lidars, magnetometers, and optical imagers that complement sounding rocket measurements of the upper atmosphere and near-Earth space environment.",
    start_year: 1968,
    status: "Current",
    source_id: "SRC-007",
    confidence_level: "High",
  },

  // ── SITE-009: Tonopah Test Range ──
  {
    activity_id: "ACT-030",
    site_id: "SITE-009",
    activity_category: "Missile Test",
    activity_description:
      "Non-nuclear ordnance testing, weapon delivery accuracy testing for nuclear weapon shapes, and ballistic trajectory studies supporting NNSA stockpile stewardship. Tests include gravity bomb drop tests, penetrator weapons, and fuzing/firing system evaluations.",
    missile_or_system_type: "B61, B83, gravity bombs, penetrator weapons",
    start_year: 1957,
    status: "Current",
    source_id: "SRC-008",
    confidence_level: "Medium",
  },
  {
    activity_id: "ACT-031",
    site_id: "SITE-009",
    activity_category: "Radar Tracking",
    activity_description:
      "Precision radar tracking and scoring of weapon test units during ballistic drop tests. Tracking radars, cinetheodolites, and GPS provide high-accuracy trajectory and impact point data for weapon certification.",
    start_year: 1957,
    status: "Current",
    source_id: "SRC-008",
    confidence_level: "Medium",
  },
  {
    activity_id: "ACT-032",
    site_id: "SITE-009",
    activity_category: "Aerospace Test",
    activity_description:
      "Parachute-retarded weapon system testing, cluster munition dispense testing, and aerodynamic characterization of weapon shapes. Historical F-117 stealth fighter operational base (1982-1988, classified).",
    start_year: 1957,
    status: "Current",
    source_id: "SRC-008",
    confidence_level: "Medium",
  },

  // ── SITE-010: Pacific Spaceport Complex – Alaska ──
  {
    activity_id: "ACT-033",
    site_id: "SITE-010",
    activity_category: "Space Launch",
    activity_description:
      "Orbital and suborbital launches for polar, sun-synchronous, and high-inclination orbit missions. First orbital launch from a non-federal range in 2001 (Athena I). Supports commercial and government payloads.",
    start_year: 1998,
    status: "Current",
    source_id: "SRC-009",
    confidence_level: "Medium",
  },
  {
    activity_id: "ACT-034",
    site_id: "SITE-010",
    activity_category: "Missile Defense",
    activity_description:
      "Missile Defense Agency target missile launches for GMD and Aegis BMD intercept testing. Intermediate-range ballistic missile targets are launched toward the Kwajalein Atoll impact area for Ground-Based Midcourse Defense tests.",
    missile_or_system_type: "IRBM target vehicles, GMD targets",
    start_year: 2001,
    status: "Current",
    source_id: "SRC-009",
    confidence_level: "Medium",
  },
  {
    activity_id: "ACT-035",
    site_id: "SITE-010",
    activity_category: "Range Safety",
    activity_description:
      "Independent range safety operations under FAA launch license. PSCA operates its own tracking radar, telemetry, and flight termination systems without reliance on a federal range.",
    start_year: 1998,
    status: "Current",
    source_id: "SRC-009",
    confidence_level: "Medium",
  },
];

export const seedContacts: Contact[] = [
  {
    contact_id: "CON-001",
    site_id: "SITE-001",
    organization_name: "White Sands Missile Range Public Affairs",
    contact_type: "Public Affairs",
    contact_url: "https://www.wsmr.army.mil/PAO/",
    source_id: "SRC-001",
  },
  {
    contact_id: "CON-002",
    site_id: "SITE-002",
    organization_name: "Vandenberg SFB Public Affairs",
    contact_type: "Public Affairs",
    contact_url: "https://www.vandenberg.spaceforce.mil/Contact-Us/",
    source_id: "SRC-002",
  },
  {
    contact_id: "CON-003",
    site_id: "SITE-003",
    organization_name: "Space Launch Delta 45 Public Affairs",
    contact_type: "Public Affairs",
    contact_url: "https://www.patrick.spaceforce.mil/Contact-Us/",
    source_id: "SRC-003",
  },
  {
    contact_id: "CON-004",
    site_id: "SITE-004",
    organization_name: "Reagan Test Site Public Affairs - USAKA",
    contact_type: "Public Affairs",
    contact_url: "https://www.smdc.army.mil/",
    source_id: "SRC-010",
  },
  {
    contact_id: "CON-005",
    site_id: "SITE-005",
    organization_name: "PMRF Public Affairs Office",
    contact_type: "Public Affairs",
    contact_url:
      "https://www.cnic.navy.mil/regions/cnrh/installations/pacific-missile-range-facility.html",
    source_id: "SRC-004",
  },
  {
    contact_id: "CON-006",
    site_id: "SITE-006",
    organization_name: "NASA Wallops Public Affairs",
    contact_type: "Public Affairs",
    contact_email: "wallops-public-inquiries@mail.nasa.gov",
    contact_url: "https://www.nasa.gov/wallops",
    source_id: "SRC-005",
  },
  {
    contact_id: "CON-007",
    site_id: "SITE-007",
    organization_name: "96th Test Wing Public Affairs",
    contact_type: "Public Affairs",
    contact_url: "https://www.eglin.af.mil/Contact-Us/",
    source_id: "SRC-006",
  },
  {
    contact_id: "CON-008",
    site_id: "SITE-008",
    organization_name:
      "Poker Flat Research Range - Geophysical Institute",
    contact_type: "General Info",
    contact_url:
      "https://www.gi.alaska.edu/facilities/poker-flat-research-range",
    source_id: "SRC-007",
  },
  {
    contact_id: "CON-009",
    site_id: "SITE-009",
    organization_name: "Sandia National Laboratories - Tonopah Test Range",
    contact_type: "General Info",
    contact_url:
      "https://www.sandia.gov/about/locations/tonopah-test-range/",
    source_id: "SRC-008",
  },
  {
    contact_id: "CON-010",
    site_id: "SITE-010",
    organization_name: "Alaska Aerospace Corporation",
    contact_type: "General Info",
    contact_url: "https://akaerospace.com/spaceport/",
    source_id: "SRC-009",
  },
];
