import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

/**
 * GET /api/import-template
 *
 * Streams `data/import-template.xlsx` so the operator can download a
 * ready-to-fill workbook from the /import page. The file is generated by
 * `npm run build:template` (scripts/build-import-template.ts) and ships
 * inside the standalone zip — this endpoint just serves it.
 *
 * 404 if the file is missing (e.g. someone deleted it from data/), so the
 * UI can surface a clear "run build:template" message instead of returning
 * an empty stream.
 */
export async function GET() {
  const filePath = path.join(process.cwd(), "data", "import-template.xlsx");
  if (!fs.existsSync(filePath)) {
    return NextResponse.json(
      { error: "Template file not found. Run `npm run build:template` to regenerate." },
      { status: 404 },
    );
  }
  const buffer = fs.readFileSync(filePath);
  return new NextResponse(buffer, {
    status: 200,
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": 'attachment; filename="LapamRanges-import-template.xlsx"',
      "Content-Length": String(buffer.length),
      "Cache-Control": "no-store",
    },
  });
}
